#ifndef SYSCALL_H
#define SYSCALL_H

#define SYS_read                   0L
#define SYS_write                  1L
#define SYS_open                   2L
#define SYS_close                  3L
#define SYS_stat                   4L
#define SYS_fstat                  5L
#define SYS_lstat                  6L
#define SYS_poll                   7L
#define SYS_lseek                  8L
#define SYS_mmap                   9L
#define SYS_mprotect               10L
#define SYS_munmap                 11L
#define SYS_brk                    12L
#define SYS_rt_sigaction           13L
#define SYS_rt_sigprocmask         14L
#define SYS_rt_sigreturn           15L
#define SYS_ioctl                  16L
#define SYS_pread64                17L
#define SYS_pwrite64               18L
#define SYS_readv                  19L
#define SYS_writev                 20L
#define SYS_access                 21L
#define SYS_pipe                   22L
#define SYS_select                 23L
#define SYS_sched_yield            24L
#define SYS_mremap                 25L
#define SYS_msync                  26L
#define SYS_mincore                27L
#define SYS_madvise                28L
#define SYS_shmget                 29L
#define SYS_shmat                  30L
#define SYS_shmctl                 31L
#define SYS_dup                    32L
#define SYS_dup2                   33L
#define SYS_pause                  34L
#define SYS_nanosleep              35L
#define SYS_getitimer              36L
#define SYS_alarm                  37L
#define SYS_settimer               38L
#define SYS_getpid                 39L
#define SYS_sendfile               40L
#define SYS_socket                 41L
#define SYS_connect                42L
#define SYS_accept                 43L
#define SYS_sendto                 44L
#define SYS_recvfrom               45L
#define SYS_sendmsg                46L
#define SYS_recvmsg                47L
#define SYS_shutdown               48L
#define SYS_bind                   49L
#define SYS_listen                 50L
#define SYS_getsockname            51L
#define SYS_getpeername            52L
#define SYS_socketpair             53L
#define SYS_setsockopt             54L
#define SYS_getsockopt             55L
#define SYS_clone                  56L
#define SYS_fork                   57L
#define SYS_vfork                  58L
#define SYS_execve                 59L
#define SYS_exit                   60L
#define SYS_wait4                  61L
#define SYS_kill                   62L
#define SYS_uname                  63L
#define SYS_semget                 64L
#define SYS_semop                  65L
#define SYS_semctl                 66L
#define SYS_shmdt                  67L
#define SYS_msgget                 68L
#define SYS_msgsnd                 69L
#define SYS_msgrcv                 70L
#define SYS_msgctl                 71L
#define SYS_fcntl                  72L
#define SYS_flock                  73L
#define SYS_fsync                  74L
#define SYS_fdatasync              75L
#define SYS_truncate               76L
#define SYS_ftruncate              77L
#define SYS_getdents               78L
#define SYS_getcwd                 79L
#define SYS_chdir                  80L
#define SYS_fchdir                 81L
#define SYS_rename                 82L
#define SYS_mkdir                  83L
#define SYS_rmdir                  84L
#define SYS_creat                  85L
#define SYS_link                   86L
#define SYS_unlink                 87L
#define SYS_symlink                88L
#define SYS_readlink               89L
#define SYS_chmod                  90L
#define SYS_fchmod                 91L
#define SYS_chown                  92L
#define SYS_fchown                 93L
#define SYS_lchown                 94L
#define SYS_umask                  95L
#define SYS_gettimeofday           96L
#define SYS_getrlimit              97L
#define SYS_getrusage              98L
#define SYS_sysinfo                99L
#define SYS_times                  100L
#define SYS_ptrace                 101L
#define SYS_getuid                 102L
#define SYS_syslog                 103L
#define SYS_getgid                 104L
#define SYS_setuid                 105L
#define SYS_setgid                 106L
#define SYS_geteuid                107L
#define SYS_getegid                108L
#define SYS_setpgid                109L
#define SYS_getppid                110L
#define SYS_getpgrp                111L
#define SYS_setsid                 112L
#define SYS_setreuid               113L
#define SYS_setregid               114L
#define SYS_getgroups              115L
#define SYS_setgroups              116L
#define SYS_setresuid              117L
#define SYS_getresuid              118L
#define SYS_setresgid              119L
#define SYS_getresgid              120L
#define SYS_getpgid                121L
#define SYS_setfsuid               122L
#define SYS_setfsgid               123L
#define SYS_getsid                 124L
#define SYS_capget                 125L
#define SYS_capset                 126L
#define SYS_rt_sigpending          127L
#define SYS_rt_sigtimedwait        128L
#define SYS_rt_sigqueueinfo        129L
#define SYS_rt_sigsuspend          130L
#define SYS_sigaltstack            131L
#define SYS_utime                  132L
#define SYS_mknod                  133L
#define SYS_uselib                 134L
#define SYS_personality            135L
#define SYS_ustat                  136L
#define SYS_statfs                 137L
#define SYS_fstatfs                138L
#define SYS_sysfs                  139L
#define SYS_getpriority            140L
#define SYS_setpriority            141L
#define SYS_sched_setparam         142L
#define SYS_sched_getparam         143L
#define SYS_sched_setscheduler     144L
#define SYS_sched_getscheduler     145L
#define SYS_sched_get_priority_max 146L
#define SYS_sched_get_priority_min 147L
#define SYS_sched_rr_get_interval  148L
#define SYS_mlock                  149L
#define SYS_munlock                150L
#define SYS_mlockall               151L
#define SYS_munlockall             152L
#define SYS_vhangup                153L
#define SYS_modify_ldt             154L
#define SYS_pivot_root             155L
#define SYS__sysctl                156L
#define SYS_prctl                  157L
#define SYS_arch_prctl             158L
#define SYS_adjtimex               159L
#define SYS_setrlimit              160L
#define SYS_chroot                 161L
#define SYS_sync                   162L
#define SYS_acct                   163L
#define SYS_settimeofday           164L
#define SYS_mount                  165L
#define SYS_umount2                166L
#define SYS_swapon                 167L
#define SYS_swapoff                168L
#define SYS_reboot                 169L
#define SYS_sethostname            170L
#define SYS_setdomainname          171L
#define SYS_iopl                   172L
#define SYS_ioperm                 173L
#define SYS_create_module          174L
#define SYS_init_module            175L
#define SYS_delete_module          176L
#define SYS_get_kernel_syms        177L
#define SYS_query_module           178L
#define SYS_quotactl               179L
#define SYS_nfsservctl             180L
#define SYS_getpmsg                181L
#define SYS_putpmsg                182L
#define SYS_afs_syscall            183L
#define SYS_tuxcall                184L
#define SYS_security               185L
#define SYS_gettid                 186L
#define SYS_readahead              187L
#define SYS_setxattr               188L
#define SYS_lsetxattr              189L
#define SYS_fsetxattr              190L
#define SYS_getxattr               191L
#define SYS_lgetxattr              192L
#define SYS_fgetxattr              193L
#define SYS_listxattr              194L
#define SYS_llistxattr             195L
#define SYS_flistxattr             196L
#define SYS_removexattr            197L
#define SYS_lremovexattr           198L
#define SYS_fremovexattr           199L
#define SYS_tkill                  200L
#define SYS_time                   201L
#define SYS_futex                  202L
#define SYS_sched_setaffinity      203L
#define SYS_sched_getaffinity      204L
#define SYS_set_thread_area        205L
#define SYS_io_setup               206L
#define SYS_io_destroy             207L
#define SYS_io_getevents           208L
#define SYS_io_submit              209L
#define SYS_io_cancel              210L
#define SYS_get_thread_area        211L
#define SYS_lookup_dcookie         212L
#define SYS_epoll_create           213L
#define SYS_epoll_ctl_old          214L
#define SYS_epoll_wait_old         215L
#define SYS_remap_file_pages       216L
#define SYS_getdents64             217L
#define SYS_set_tid_address        218L
#define SYS_restart_syscall        219L
#define SYS_semtimedop             220L
#define SYS_fadvise64              221L
#define SYS_timer_create           222L
#define SYS_timer_settime          223L
#define SYS_timer_gettime          224L
#define SYS_timer_getoverrun       225L
#define SYS_timer_delete           226L
#define SYS_clock_settime          227L
#define SYS_clock_gettime          228L
#define SYS_clock_getres           229L
#define SYS_clock_nanosleep        230L
#define SYS_exit_group             231L
#define SYS_epoll_wait             232L
#define SYS_epoll_ctl              233L
#define SYS_tgkill                 234L
#define SYS_utimes                 235L
#define SYS_vserver                236L
#define SYS_mbind                  237L
#define SYS_set_mempolicy          238L
#define SYS_get_mempolicy          239L
#define SYS_mq_open                240L
#define SYS_mq_unlink              241L
#define SYS_mq_timedsend           242L
#define SYS_mq_timedreceive        243L
#define SYS_mq_notify              244L
#define SYS_mq_getsetattr          245L
#define SYS_kexec_load             246L
#define SYS_waitid                 247L
#define SYS_add_key                248L
#define SYS_request_key            249L
#define SYS_keyctl                 250L
#define SYS_ioprio_set             251L
#define SYS_ioprio_get             252L
#define SYS_inotify_init           253L
#define SYS_inotify_add_watch      254L
#define SYS_inotify_rm_watch       255L
#define SYS_migrate_pages          256L
#define SYS_openat                 257L
#define SYS_mkdirat                258L
#define SYS_mknodat                259L
#define SYS_fchownat               260L
#define SYS_futimesat              261L
#define SYS_newfstatat             262L
#define SYS_unlinkat               263L
#define SYS_renameat               264L
#define SYS_linkat                 265L
#define SYS_symlinkat              266L
#define SYS_readlinkat             267L
#define SYS_fchmodat               268L
#define SYS_faccessat              269L
#define SYS_pselect6               270L
#define SYS_ppoll                  271L
#define SYS_unshare                272L
#define SYS_set_robust_list        273L
#define SYS_get_robust_list        274L
#define SYS_splice                 275L
#define SYS_tee                    276L
#define SYS_sync_file_range        277L
#define SYS_vmsplice               278L
#define SYS_move_pages             279L
#define SYS_utimensat              280L
#define SYS_epoll_pwait            281L
#define SYS_signalfd               282L
#define SYS_timerfd_create         283L
#define SYS_eventfd                284L
#define SYS_fallocate              285L
#define SYS_timerfd_settime        286L
#define SYS_timerfd_gettime        287L
#define SYS_accept4                288L
#define SYS_signalfd4              289L
#define SYS_eventfd2               290L
#define SYS_epoll_create1          291L
#define SYS_dup3                   292L
#define SYS_pipe2                  293L
#define SYS_inotify_init1          294L
#define SYS_preadv                 295L
#define SYS_pwritev                296L
#define SYS_rt_tgsigqueueinfo      297L
#define SYS_perf_event_open        298L
#define SYS_recvmmsg               299L
#define SYS_fanotify_init          300L
#define SYS_fanotify_mark          301L
#define SYS_prlimit64              302L
#define SYS_name_to_handle_at      303L
#define SYS_open_by_handle_at      304L
#define SYS_clock_adjtime          305L
#define SYS_syncfs                 306L
#define SYS_sendmmsg               307L
#define SYS_setns                  308L
#define SYS_getcpu                 309L
#define SYS_process_vm_readv       310L
#define SYS_process_vm_writev      311L
#define SYS_kcmp                   312L
#define SYS_finit_module           313L
#define SYS_sched_setattr          314L
#define SYS_sched_getattr          315L
#define SYS_renameat2              316L
#define SYS_seccomp                317L
#define SYS_getrandom              318L
#define SYS_memfd_create           319L
#define SYS_kexec_file_load        320L
#define SYS_bpf                    321L
#define SYS_execveat               322L
#define SYS_userfaultfd            323L
#define SYS_membarrier             324L
#define SYS_mlock2                 325L
#define SYS_copy_file_range        326L
#define SYS_preadv2                327L
#define SYS_pwritev2               328L
#define SYS_pkey_mprotect          329L
#define SYS_pkey_alloc             330L
#define SYS_pkey_free              331L
#define SYS_statx                  332L
#define SYS_io_pgetevents          333L
#define SYS_rseq                   334L

#endif /* SYSCALL_H */
